java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/MethodCallSymbolProvider.java
When getting methods with type erasure, you get a ton of results.
We may in the future, want to make this optional:
This is what an inaccurate search is: 
```
The search result is potentially a match for the search pattern,
but the search engine is unable to fully check it (for example, because
there are errors in the code or the classpath are not correctly set).
```
=> :bug: adding accuracy to the method

.github/workflows/multi-arch_images_build.yaml, .github/workflows/update_maven_index.yaml, Dockerfile, hack/Dockerfile, hack/export.java
This should speed up builds both locally and in GH actions. It also solves problems for downstream.
I also believe we're missing some valid entries with the other script trying to run over the binary file. For instance, `org.apache.karaf.cellar.samples.dosgi.greeter.*` was added and bad versions of this beginning with q, t, and u were removed.
The PR from a test run here shows what look like a bunch of valid entries being added and invalid entries being removed.
https://github.com/jmontleon/java-analyzer-bundle/commit/176aada5667d1d3a51c108b04ec4e7c91eae01ba
=> :ghost: Fix maven index and update it weekly

hack/Dockerfile, hack/export.java
This gets rid of all the piping, compressing, uncompressing, grep/sort/awk stuff, speeds things up a little and adds some more missing entries.
Example run:
https://github.com/jmontleon/java-analyzer-bundle/actions/runs/6113603987/job/16593418996
Results compared to previous run:
https://github.com/jmontleon/java-analyzer-bundle/commit/32a3bb2a8a4dd3cdcb0f9049160e96b557b877d9
=> :ghost: Improve maven.default.index gen

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java
Adding the ability to look at accuracy if and only if, there is not a wildcard in the search.
=> adding ability to determine if match is accurate if not a pattern match

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java
When an annotation is requested (symbolKind 4) then we should skip exact matches.
=> Adding an out for when a annotation is requested

Dockerfile
For the analyzer to be able to run `mvn dependency:...` without the need for compilation, we need to upgrade maven to a newer version.
Related to https://github.com/konveyor/analyzer-lsp/issues/393
=> Upgrade maven to 3.9.5

Dockerfile
With this change we can at least run as non-root.
I would also proprose moving binaries that need to be accessible to all users be installed in /usr/local/bin. But as of right now it seems we have configs hard coded to this location.
https://github.com/konveyor/java-analyzer-bundle/blob/main/Dockerfile#L41
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html
https://github.com/konveyor/analyzer-lsp/blob/f6cdf400bf2c7e236b050f31300e9e504e241d78/provider_settings.json.sample#L8
We could probably keep the handling to /root/.m2 similar, except update the permissions changes to only  adjust /root/.m2. Alternatively, set HOME=/ and set it up and adjust permissions there instead of linking it.
=> :ghost: Improve running as non-root

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/MethodCallSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/TypeSymbolProvider.java
This removes accuracy checks that depend on errors in the project. 
I observed that most inaccurate matches we get are from TypeReferenceMatch matches, this is because they do not take into account fully qualified names of types. 
There is also some instances of inaccurate stuff coming from method calls, this fixes the search pattern to be fully qualified instead of all references.
=> :bug: check accuracy of TypeReferenceMatch & MethodReferenceMatch

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/RuleEntryParams.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java
This adds ability to create a search scope from file paths, and also disables test files from scope (this is the first true argument to createSearchScope function). Note that the search scope can only be set at a package level. Haven't yet figured out how to get it down to compilation units. But I think this is enough for now.
=> :sparkles: add ability to set search scope by file paths

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/ConstructorCallSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/CustomASTVisitor.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/MethodCallSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/SymbolProvider.java
This PR improves accuracy of some searches: 
* METHOD_CALL / MethodReference: we try to match fqn of the method. 
* CONSTRUCTOR_CALL / MethodReference: same as above
=> :bug: improve accuracy of MethodReference matches

.github/workflows/global-ci.yaml, Dockerfile, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/ConstructorCallSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/CustomASTVisitor.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/MethodCallSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/SymbolProvider.java, java-analyzer-bundle.tp/java-analyzer-bundle.target
API Tests PR: 155
This specifically addresses cases with queries containing FQN searches and/or *. We get more symbols than needed from jdt in these cases, we add logic to filter-out matches by inspecting full names of symbols.
=> :bug: Improve accuracy of METHOD_CALL and CONSTRUCTOR_CALL matches

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java
=> :bug: handle when a default search will have invalid query 

Dockerfile, jdtls-bin-override/jdtls.py
Setting max RAM to 70% and keeping the min to 1 GB that means that the minimum that you can run the pod with is 1.5 GB, but I still think we should use 2 GB memory and document that this is the minimum requirement. 
Creating a documentation task to track this, and follow up PRs' to change the numbers once this merges.
For now you should see about 3GB of max space for the process to use until the limits are turned down.
=> :bug: Adding settings to the init script for jdtls

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/SymbolProvider.java
Should fix https://github.com/konveyor/analyzer-lsp/issues/693
`System.out.println` will never match because `out` is a static field that references another class (`java.io.PrintStream`), but this should fix the rest of the cases.
=> Fix METHOD_CALL location in queryQualificationMatches

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/RuleEntryParams.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/query/AnnotationQuery.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/AnnotationSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/WithAnnotationQuery.java
Also enables to match annotations within annotations.
- Fixes https://github.com/konveyor/analyzer-lsp/issues/655
=> Allow annotation queries to happen in ANNOTATION location

Dockerfile, java-analyzer-bundle.tp/java-analyzer-bundle.target
Resolves `No repository found at https://download.eclipse.org/jdtls/snapshots/repository/1.36.0.202405301306`
=> Upgrade eclipse

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java
Absolute paths can be to modules or individual files
=> :sparkles: Adding ability for the handled paths to be abosolute paths

java-analyzer-bundle.tp/java-analyzer-bundle.target
Need to use the latest release build, that is consistant with the java version of 17.
=> Fixing the build

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/MethodCallSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/SymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/SymbolProviderResolver.java
* We need to make sure that the compilation unit is consistant with the underlying resource before we look for the location.
* Changes to the filesystem are reflected correctly in the search match, but are not reflected in the compilation unit, so we need to force it to become consistant.
* Fixed a bug in a regex replace that caused every char to be changed to "/"
* Fixed a potential bug, where for a multipattern seach match, we could have overwrites of the specific SymbolProvider.
fixes #122
=> :bug: Make compilation unit consistant with underlying resource

.github/workflows/global-ci.yaml, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/ConstructorCallSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/MethodCallSymbolProvider.java
follow on for #123 to make the function work you have to close the working copy after you use it.
=> :bug: closing the compilation unit is needed for make consistant to work

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/ConstructorCallSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/MethodCallSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/TypeSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/WorkingCopyOwnerImpl.java, java-analyzer-bundle.tp/java-analyzer-bundle.target
- Update code to remove usage of deprecated method call.
- Close compilation units properly when not using them anymore.
- Update dependency due to broken build.
https://issues.redhat.com/browse/MTA-4943
=> Close compilation units, do not use deprecated members, fix deps

.gitignore, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/RuleEntryParams.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/util/OpenSourceFilteredSearchScope.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/util/OpenSourceLibraryExclusionManager.java
=> :bug: use maven local repo path to accurately exclude libraries alone (#131)
