konveyor/java-analyzer-bundle

.gitignore, .project, .vscode/extensions.json, java-analyzer-bundle.core/.classpath, java-analyzer-bundle.core/.project, java-analyzer-bundle.core/.settings/org.eclipse.core.resources.prefs, java-analyzer-bundle.core/.settings/org.eclipse.jdt.core.prefs, java-analyzer-bundle.core/.settings/org.eclipse.m2e.core.prefs, java-analyzer-bundle.site/.project, java-analyzer-bundle.site/.settings/org.eclipse.core.resources.prefs, java-analyzer-bundle.site/.settings/org.eclipse.m2e.core.prefs, java-analyzer-bundle.test/.classpath, java-analyzer-bundle.test/.project, java-analyzer-bundle.test/.settings/org.eclipse.core.resources.prefs, java-analyzer-bundle.test/.settings/org.eclipse.jdt.core.prefs, java-analyzer-bundle.test/.settings/org.eclipse.m2e.core.prefs, java-analyzer-bundle.tp/.project, java-analyzer-bundle.tp/.settings/org.eclipse.core.resources.prefs, java-analyzer-bundle.tp/.settings/org.eclipse.m2e.core.prefs, java-analyzer-bundle.tp/java-analyzer-bundle.target, java-analyzer-bundle.tp/pom.xml, javaConfig.json, pom.xml
couple of issues to fix:
- ~JUnit tests don't output anything in the console, you need to inspect the surefire-reports to see what happened~ test output works now
- ~vscode-java fails to load the TP properly so far~ As a workaround for https://github.com/eclipse-pde/eclipse.pde/issues/207, I had to copy the content of the jdt.ls TP into this TP
Signed-off-by: Fred Bricon <fbricon@gmail.com>
=> build: fix target platform

.github/workflows/multi-arch_images_build.yaml, .gitignore, Dockerfile, java-analyzer-bundle.core/.project, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java, java-analyzer-bundle.test/.project
fixes #11 
fixes #12 
Also adds a dockerfile to build the base image. A follow up PR to add github actions here to build the image and push to quay will be added.
=> Adding ablity to search for methods and constructors

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java
fixes #16 
Signed-off-by: Shawn Hurley <smhurley00@gmail.com>
=> ✨ Adding ability to handle searching inheritance and implmentors

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java
fixes #15 
Signed-off-by: Shawn Hurley <smhurley00@gmail.com>
=> adding ability to handle searching for imports

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java
fixes #19 
Signed-off-by: Shawn Hurley <shawn@hurley.page>
=> adding ability to handle the local variable search

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java
Signed-off-by: Shawn Hurley <shawn@hurley.page>
=> adding ability to query for method return

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java
Signed-off-by: Shawn Hurley <shawn@hurley.page>
=> fixes method call to find references of the method

java-analyzer-bundle.core/META-INF/MANIFEST.MF, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java
* another fix for finding type erasure matches
=> Adding ability to wait for sources to be downloaded

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/ConstructorCallSymbolProvider.java
1. Adding the ability for the constructor method provider to handle when the enclosing element is not a constructor but the match is for a constructor.
=> :sparkles: Adding ability to handle list of searches following the  format

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/ConstructorCallSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/DefaultSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/SymbolProviderResolver.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/TypeSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/VariableDeclarationSymbolProvider.java, java-analyzer-bundle.tp/java-analyzer-bundle.target
Adding a new type provider and making sure that if nothing is found for a given provider that it returns null.
=> :sparkles: adding ability to search for everything by default

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/DefaultSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/MethodCallSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/WithMaxResults.java
Adding all the matches for a default search as well
=> Adding ability to handle querys with *

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/AnnotationSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/ConstructorCallSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/DefaultSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/ImplementsTypeSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/ImportSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/InheritanceSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/MethodCallSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/ReturnTypeSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/TypeSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/VariableDeclarationSymbolProvider.java
Also updating dealing with symbol kind to make sure that it works correctly
=> Need to have some defaults, remove java system scope

Dockerfile
Adding fernflower to the bundle will help us when we need to decompile Java files.
=> :sparkles: Add fernflower to bundle

Dockerfile, java-analyzer-bundle.tp/java-analyzer-bundle.target
=> :sparkles: add maven index

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/ReferenceSymbolProvider.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/symbol/SymbolProviderResolver.java, java-analyzer-bundle.tp/java-analyzer-bundle.target
Adding the ability to search for package references. 
For instance, searching for `ilog.*` will match everything that comes from that package.
=> :sparkles: Adding package search functionality

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java
needed for fixing https://github.com/konveyor/analyzer-lsp/issues/361
=> :bug: Adding filter to filter out doc comment matches

hack/maven.default.index, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java
=> :GHOST: Release 0.3

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SymbolInformationTypeRequestor.java
fixes https://github.com/konveyor/analyzer-lsp/issues/378
=> :bug: When there are errors in the resource files matches are always inaccurate

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java
- Fixes https://github.com/konveyor/analyzer-lsp/issues/622
=> Enable field search

java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java
Reverts konveyor/java-analyzer-bundle#99
=> Revert "Revert "Enable field search""

.gitignore, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/RuleEntryParams.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/util/OpenSourceFilteredSearchScope.java, java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/util/OpenSourceLibraryExclusionManager.java
=> :bug: use maven local repo path to accurately exclude directories

Dockerfile
=> Update Dockerfile to use mvn 3.9.10

Dockerfile
(cherry picked from commit d527decc20fae711fbed6b7d8160b42945753bf7)
=> Update Dockerfile to use mvn 3.9.10 (#134)
